### ISSUE TITLE
Profile updating and data propagation (if that is the word for this)

### ISSUE THREAD

**Issue by dcarr001** [nmsu-cs/project-circle-of-business-friends#4]
How do we make sure that if a user, A, updates their profile, and another user, B,  is logged in and viewing any info about that user, the updated A information is viewable to B? This I think would mean we have to test if two of us can update information, and someone else can immediately view the information that we added without exiting the script.

**Comment by Jodansky** [comment]
https://stackoverflow.com/questions/16344756/auto-reloading-python-flask-app-upon-code-changes/40150705#40150705
Just use the built in dev server, open 2 instances, and check like that.

**Comment by dcarr001** [comment]
Cool thx
