### ISSUE TITLE
Frequency of executing matching algorithm

### ISSUE THREAD

**Issue by dcarr001** [nmsu-cs/project-circle-of-business-friends#5]
How often should the matching algorithm be run? Just so we have an idea when it comes to development. The way the database is set up right now is match_id, user_id, matched_user_id. My idea right now is to execute the algorithm whenever an update occurs but I don't know if that will become computationally intensive or if anyone of y'all have a better idea.

**Comment by pattyl11** [comment]
I expect to see assignees to each and every issue in the repo. If no one takes it @dcarr001, assign it to someone.

**Comment by pattyl11** [comment]
@tomalewski @SmallBrainMatt

**Comment by carsonSiegrist** [comment]
I'm no expert - but I think we can just run it whenever a user requests it? Like when they go to whatever page where you browse matches, generate X matches, and if the user runs through them, generate more. 

With our small dataset, our matching algo doesn't even need to be that fast for this to be viable, we really would just need  like <1sec load time.

**Comment by dcarr001** [comment]
yeah just finished the algorithm, not expensive at all, so itll just update whenever a user updates their profile page.
